# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import inference_pb2 as proto_dot_inference__pb2


class InferenceServiceStub(object):
    """Service definition for AI model inference
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/inference.InferenceService/Classify',
                request_serializer=proto_dot_inference__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.ClassifyResponse.FromString,
                )


class InferenceServiceServicer(object):
    """Service definition for AI model inference
    """

    def Classify(self, request, context):
        """Classify iris flowers using the trained model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=proto_dot_inference__pb2.ClassifyRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.ClassifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Service definition for AI model inference
    """

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/inference.InferenceService/Classify',
            proto_dot_inference__pb2.ClassifyRequest.SerializeToString,
            proto_dot_inference__pb2.ClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
