# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/inference.proto\x12\tinference\"g\n\x0f\x43lassifyRequest\x12\x14\n\x0csepal_length\x18\x01 \x01(\x02\x12\x13\n\x0bsepal_width\x18\x02 \x01(\x02\x12\x14\n\x0cpetal_length\x18\x03 \x01(\x02\x12\x13\n\x0bpetal_width\x18\x04 \x01(\x02\"\xbe\x01\n\x10\x43lassifyResponse\x12\x17\n\x0fpredicted_class\x18\x01 \x01(\t\x12\x1d\n\x15predicted_class_index\x18\x02 \x01(\x05\x12\x15\n\rprobabilities\x18\x03 \x03(\x02\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\x13\n\x0b\x61ll_classes\x18\x05 \x03(\t\x12\x32\n\x0einput_features\x18\x06 \x01(\x0b\x32\x1a.inference.ClassifyRequest2W\n\x10InferenceService\x12\x43\n\x08\x43lassify\x12\x1a.inference.ClassifyRequest\x1a\x1b.inference.ClassifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFYREQUEST']._serialized_start=36
  _globals['_CLASSIFYREQUEST']._serialized_end=139
  _globals['_CLASSIFYRESPONSE']._serialized_start=142
  _globals['_CLASSIFYRESPONSE']._serialized_end=332
  _globals['_INFERENCESERVICE']._serialized_start=334
  _globals['_INFERENCESERVICE']._serialized_end=421
# @@protoc_insertion_point(module_scope)
